matrix:
  fast_finish: true
  include:

    - os: osx
      osx_image: xcode8
      language: c++
      compiler: clang
      env:
        - BUILD_NAME=good-case
    - os: osx
      osx_image: xcode8
      language: c++
      compiler: clang
      env:
        - BUILD_NAME=bad-case

script:
  - ./${BUILD_NAME}.sh


